### ISSUE TITLE
Duplicate Error Reports between Sentry.LoggerBackend & Sentry.Plug

### ISSUE THREAD

**Issue by jeremyjh** [getsentry/sentry-elixir#353] opened 2019-07-09 20:08 UTC
### Environment

* Elixir version (elixir -v): 1.7.3
* Erlang/OTP version (erl): 21.0.4
* Sentry version (mix deps): 7.0.3
* Operating system: ubuntu (heroku-16) 

### Description
We receive duplicate error reports for exceptions raised in our Phoenix controllers. One contains all the context we'd expect for a web request such as the headers, params and `set_user_context` data that we supply, and the other contains almost nothing other than the exception and the stack trace.

### Expected Behavior
Only one report is logged per exception. 

### Actual Behavior
Two reports are logged for each exception.

### Steps to Reproduce

We do a `use Sentry.Plug` in our Router. We also a do a `Logger.add_backend(Sentry.LoggerBackend)` in our `Application.start` function. Are dupes expected in this scenario?
If so I'm not sure why we hadn't seen this issue before, but it is new for us. We did make a change with regard to Sentry just before this began happening, which is that we do an extra `mix deps.compile sentry --force` as part of our build to refresh sources, but that seems unlikely to be implicated.

**Comment by mitchellhenke** [comment] 2019-07-09 21:18
Thanks for opening an issue (and your work on dialyxir)!  It shouldn't duplicate in that setup, and you're correct that the compilation shouldn't have an effect.

I'm not able to reproduce this, so I have a few questions if you don't mind 🙂

Is this an umbrella application?
Did you update Sentry, Elixir or Erlang versions recently?
Could you share the JSON of the two errors (under the `JSON` link on the event page)?  I'm happy to receive that information privately on the Elixir slack (same username) or my GitHub email, and of course feel free to remove as much information as you like if there are details in the JSON you can't share.

**Comment by jeremyjh** [comment] 2019-07-09 21:41
Hi, thanks for the quick response. Some answers:

This is not an umbrella application.

We have not updated Sentry, Elixir or Erlang recently. We have updated some dependencies or transitive dependencies recently such as hackney and mimerl.

I'll share the JSONs with you on Slack.

**Comment by mitchellhenke** [comment] 2019-07-10 22:54
I think I've located the issue.  I believe it relates to the changes to `plug_cowboy` in https://github.com/elixir-plug/plug_cowboy/pull/9, which was released in version `2.0.2`.  Before that change, those processes did not include a `:crash_reason` in the Logger metadata, which meant `Sentry.LoggerBackend` did not send an error report.  Since it does now, `Sentry.LoggerBackend` will report an error alongside `Sentry.Plug`.  It's solvable, but my current ideas for potential fixes are not what I'd call "ideal" 🙂

The simpler fix would be to check if the Logger message or stacktrace seems to come from a Plug application and skip sending if that's the case (I took a quick stab at it [here](https://github.com/getsentry/sentry-elixir/compare/master...fix-plug-duplication?expand=1)).  It works for now, but depends on a specific MFA being in the stacktrace.

My other idea would be for Sentry to include its own Logger Translator, and include some extra metadata during translation so that the backend can check and skip based on that.  This is more complex and would likely have to be implemented such that users would have to install the translator themselves.

I'm happy to hear any thoughts, but I'll probably have to think on this.

**Comment by jeremyjh** [comment] 2019-07-10 23:31
That makes sense; `plug_cowboy` was bumped as well from `2.0.1` to `2.1.0`. I wish I had mentioned it but glad you found the issue. I don't think there is any rush for a fix in sentry from my side; I can probably pin `plug_cowboy` back to `2.0.1` for now.

**Closed** 2019-10-23 15:33 UTC
Labels: bug
