### ISSUE TITLE
documentation suggestion

### ISSUE THREAD

**Issue by atomkirk** [getsentry/sentry-elixir#311] opened 2018-11-06 14:12 UTC
I found that `handle_otp_reports` is enabled by default but `handle_sasl_reports` is not and that was causing us to miss A LOT of errors. Especially those running in processes or exq jobs.

I strongly suggest telling people to add 

    handle_sasl_reports: true

to their logger config so they get all erlang/elixir errors

**Comment by mitchellhenke** [comment] 2018-11-06 14:46
Thanks for opening this @atomkirk

What Sentry version and Erlang/Elixir version are you on?

**Comment by atomkirk** [comment] 2018-11-06 15:11
Sentry v7, Elixir 1.7, erlang 21.1

**Comment by atomkirk** [comment] 2018-11-08 15:40
here's one:

```
(ErlangError) Erlang error: {:EXIT, {%Protocol.UndefinedError{description: "", protocol: String.Chars, value: {:invalid, #Reference<0.3240635966.1734344705.69075>}}, [{String.Chars, :impl_for!, 1, [file: 'lib/string/chars.ex', line: 3]}, {String.Chars, :to_string, 1, [file: 'lib/string/chars.ex', line: 22]}, {LogstashJson.TCP, :log_event, 5, [file: 'lib/logstash_json_tcp.ex', line: 63]}, {LogstashJson.TCP, :handle_event, 2, [file: 'lib/logstash_json_tcp.ex', line: 42]}, {:gen_event, :server_update, 4, [file: 'gen_event.erl', line: 577]}, {:gen_event, :server_notify, 4, [file: 'gen_event.erl', line: 559]}, {:gen_event, :server_notify, 4, [file: 'gen_event.erl', line: 561]}, {:gen_event, :handle_msg, 6, [file: 'gen_event.erl', line: 300]}, {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 249]}]}}
```

**Comment by atomkirk** [comment] 2018-11-08 15:49
Here's another one:

![](https://d.pr/i/qpBL9A+)

On that one, I actually used [Exq](https://github.com/akira/exq) Middelware (`after_failed_work`) hook to add the extra (eg `job_serialized`) info and send the error manually. We weren't getting errors in exq jobs for months before adding this.

using `handle_sasl_reports: true` did actually start sending the error above, but with no sentry context, so they are very unhelpful errors. So, we also send the error in the exq hook like I described sending the job data to help debug.

**Comment by mitchellhenke** [comment] 2018-11-08 17:04
SASL was [deprecated](http://erlang.org/doc/apps/sasl/error_logging.html) in Erlang 21, so I would like to exhaust other solutions before suggesting using it in documentation.

In testing Exq in a sample application, Sentry catches failed jobs for me (though not with the job metadata):
![image](https://user-images.githubusercontent.com/1430443/48214504-b7298400-e345-11e8-9073-dcc876816d29.png)


Do you have `Sentry.LoggerBackend` configured as described [here](https://github.com/getsentry/sentry-elixir#capture-crashed-process-exceptions)?

**Comment by atomkirk** [comment] 2018-11-08 17:10
I do. Whats going on here is kind of complicated. 
1) There are errors we get in sentry (even some from jobs I think). 
2) errors we get only in kibana (our logging backend)
3) errors we get in neither unless handle_sasl_reports is turned on

So, I think we could survive without all the SASL reports. They aren't super high quality errors. But it does make me wonder if there is a bug with `Sentry.LoggerBackend`

Actually, in my experimentation, I was able to reproduce a few errors that went to the logger backend but didn't have the `crash_reason` tuple UNLESS I had `handle_sasl_reports: true`. Thats why for months we've been seeing errors in Kibana but not Sentry, because Kibana doesnt ignore them if they dont' have a `crash_reason`. So, I wrote my own logger to replace `Sentry.LoggerBackend`, thinking I would send them all to sentry even without a `crash_reason`, but when I tried turning on `handle_sasl_reports: true` then the crash_reason tuple was there more consistently and the sentry backend worked, so I just kept using it.

Very strange

**Comment by mitchellhenke** [comment] 2018-11-08 17:28
Thanks for the detail.  It's very possible things are missed from `crash_reason` and it can be improved, but lacking specific cases makes it more difficult.

My hunch is that the error you shared in https://github.com/getsentry/sentry-elixir/issues/311#issuecomment-437040945 is confounding things a bit, as it suggests that logs aren't making it to Logstash because it can't log the event (and crashing the Logstash Logger backend).  I wouldn't expect this to affect the Sentry Logger backend, but hopefully fixing it could clear up any crossover problems.

**Comment by atomkirk** [comment] 2018-11-08 17:31
Well its for sure not affecting the sentry logger backend, becuase that error now appears in sentry. But only if `handle_sasl_reports: true` is set.

I'll try to create an example app for you when I get some time. For now, having the setting on works for us, so I guess just having this issue will be helpful for other people who have the same issue.

**Comment by mitchellhenke** [comment] 2018-11-08 18:51
It won't affect it in some cases (like the one in the comment), but I am hesitant to say it can't affect it at all.  One possibility is Sentry caught an event, but failed to send due to a bug in Sentry and the resulting log failed to be sent to Logstash due to the error shared above.

To move forward on this issue, I think finding a case where enabling SASL catches an error that having it disabled does not catch, or a case where a process crashes and Sentry does not capture it at all is necessary.

**Comment by mitchellhenke** [comment] 2018-11-28 15:01
absent a way to reproduce, I'm closing this issue for now 🙂

**Closed** 2018-11-28 15:02 UTC
Labels: question
