### ISSUE TITLE
Sentry.LoggerBackend configuration fails - module not available

### ISSUE THREAD

**Issue by akebi** [getsentry/sentry-elixir#460] opened 2021-02-04 18:00 UTC
I was directed here by Sentry Support.

Despite several attempts, we're unable to appropriately configure Sentry (backend) logger for capturing the application messages from Elixir functions executed from the command line. Compilation results in error with missing sentry backend logger dependencies.

How do we install and configure Sentry backend logging appropriately for use with command line driven Elixir apps?

### Environment

How do you use Sentry?
Sentry SaaS (sentry.io) 

Which SDK and version?
```
elixir: "~> 1.5"
phoenix, "~> 1.5.1"
sentry, "~> 8.0.0"
```

### Steps to Reproduce

1. Add Sentry as a dependency to mix file - `sentry, "~> 8.0.0"`
2. Setup logger in `config` as described here: (https://hexdocs.pm/sentry/Sentry.LoggerBackend.html)[https://hexdocs.pm/sentry/Sentry.LoggerBackend.html]. Our configuration is as below, with sentry backend logger configured along side JSON logger:
     ```
     config :logger,
          backends: [LoggerJSON, Sentry.LoggerBackend]

     config :logger, Sentry.LoggerBackend,
          level: :warn,
         capture_log_messages: true
     ```
3. Install dependencies - `mix deps.get`
4. Compile app - `mix compile`

Also attempted to add this to re-compile Sentry again after the compilation of all other libs - `mix deps.compile sentry --force` but that didn't resolve the issue.

### Expected Result

All required dependencies to use Sentry, are installed and Elixir app compiles and messages can be captured for application code from function calls from command line jobs.

### Actual Result
When the configuration for the logger backend is added to the Elixir app config, Sentry dependency installation fails with error below:
```
"EXIT when installing backend Sentry.LoggerBackend: an exception was raised:\n ** (UndefinedFunctionError) function Sentry.LoggerBackend.init/1 is undefined (module Sentry.LoggerBackend is not available)\n Sentry.LoggerBackend.init(Sentry.LoggerBackend)\n (stdlib 3.12.1) gen_event.erl:473: :gen_event.server_add_handler/4\n (stdlib 3.12.1) gen_event.erl:318: :gen_event.handle_msg/6\n (stdlib 3.12.1) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
```
The same Sentry version compiles without issue when plug context is set for Phoenix endpoints `plug Sentry.PlugContext`

**Comment by al2o3cr** [comment] 2021-02-06 00:54
FWIW, you can also attach the backend at runtime; we have this in our main application's `start` callback:
```
{:ok, _} = Logger.add_backend(Sentry.LoggerBackend)
```
which I'd assume gets around the compile-time dependency.

**Comment by mitchellhenke** [comment] 2021-02-06 14:19
Thanks for opening an issue!

I've tried to reproduce the issue, but haven't been able to. I've configured the application as you've described and the application compiled successfully.

Does the error happen during compilation or when you're running a command line task?

**Comment by akebi** [comment] 2021-02-08 09:12
> FWIW, you can also attach the backend at runtime; we have this in our main application's `start` callback:
> 
> ```
> {:ok, _} = Logger.add_backend(Sentry.LoggerBackend)
> ```
> 
> which I'd assume gets around the compile-time dependency.
Thanks for this tip @al2o3cr - I'll definitely be giving this drive, although I imagine the missing module error indicates something might not be playing well with the library itself

**Comment by akebi** [comment] 2021-02-08 09:21
> Thanks for opening an issue!
> 
> I've tried to reproduce the issue, but haven't been able to. I've configured the application as you've described and the application compiled successfully.
> 
> Does the error happen during compilation or when you're running a command line task?

@mitchellhenke for sure, thanks for taking a look at the issue.

This is happening for us when compiling the Elixir app, with all dependencies, including Sentry, already installed.

**Comment by mitchellhenke** [comment] 2021-02-14 14:53
>This is happening for us when compiling the Elixir app, with all dependencies, including Sentry, already installed.

That's pretty odd and unexpected. Looking back, you put your Elixir version in the original post as `~> 1.5`, is that correct?

**Comment by akebi** [comment] 2021-02-15 12:30
Odd indeed. To clarify these are the Elixir app environment details:

```
Erlang/OTP 22 [erts-10.7.2.1] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1]

Elixir 1.10.3 (compiled with Erlang/OTP 22)
```

It's the version for the mix project that is set as `elixir: "~> 1.5"`

**Comment by mitchellhenke** [comment] 2021-02-28 15:01
Great, thanks for the clarification. Can you share example code that reproduces the issue? I unfortunately haven't been able to get this behavior to happen.

**Comment by akebi** [comment] 2021-03-01 20:32
Allow me to correct my information from prior, the error is raised when starting the Elixir app. Here are snippets from the config and application and a little more error context. 

```
# config/config.exs

import Config

config :logger,
  backends: [LoggerJSON, Sentry.LoggerBackend]

config :logger_json, :backend, metadata: :all

config :logger, Sentry.LoggerBackend,
  level: :warn,
  capture_log_messages: true
```

```
# app/application.ex

defmodule App.Application do
  use Application

  @impl Application
  def start(_type, _args) do
    # List all child processes to be supervised
    children =
      [
        App.Repo,
        AppWeb.Endpoint,
        # Start the task supervisor (for background jobs)
        {Task.Supervisor, name: App.TaskSupervisor}
      ] 

    opts = [strategy: :one_for_one, name: App.Supervisor]
    Supervisor.start_link(children, opts)
  end
```

and then running `mix start; mix run --no-halt` and  surfaces the error below:

```
application: logger
    exited: {{shutdown,
                 {failed_to_start_child,'Elixir.Logger.BackendSupervisor',
                     {'EXIT',
                         {#{'__exception__' => true,
                            '__struct__' => 'Elixir.RuntimeError',
                            message =>
                                <<"EXIT when installing backend Sentry.LoggerBackend: an exception was raised:\n    ** (UndefinedFunctionError) function Sentry.LoggerBackend.init/1 is undefined (module Sentry.LoggerBackend is not available)\n        Sentry.LoggerBackend.init(Sentry.LoggerBackend)\n        (stdlib 3.12.1) gen_event.erl:473: :gen_event.server_add_handler/4\n        (stdlib 3.12.1) gen_event.erl:318: :gen_event.handle_msg/6\n        (stdlib 3.12.1) proc_lib.erl:249: :proc_lib.init_p_do_apply/3">>},
```

Hopefully this is more complete and helpful in diagnosis.

**Comment by mitchellhenke** [comment] 2021-03-07 16:34
Thanks for the additional details. I generated a fresh Phoenix project, and `mix start` doesn't appear to be a defined task by default. Does that task come from another dependency?

**Comment by akebi** [comment] 2021-03-09 20:45
Ah yes, excuse me. In this case it is a custom alias, the commands as run for a new app would be:

```
mix deps.get
mix ecto.setup
mix run --no-halt
```

**Comment by mitchellhenke** [comment] 2021-03-14 17:28
Thanks! I added the configuration above and ran those commands, but wasn't able to reproduce. I am using this repository to try to track this issue down: https://github.com/mitchellhenke/phoenix_sentry_logger_error

Could you try running the commands with that repository to see if it reproduces the issue for you?

**Comment by josevalim** [comment] 2021-04-07 17:29
@mitchellhenke the issue is with releases, as the logger app will be configured early before entry is loaded. :) I sent #472 with up to date recommendations.

**Comment by akebi** [comment] 2021-04-07 20:34
thanks @mitchellhenke, following our discussions, made a few tweaks to configs and I think I finally got a working config and load order 🤞

**Comment by mitchellhenke** [comment] 2021-04-08 13:48
Thank you @josevalim! Closing this issue with the updates there 🙂

**Closed by mitchellhenke** 2021-04-08 13:48 UTC
