### ISSUE TITLE
Cannot send test event when filter applied

### ISSUE THREAD

**Issue by hawksight** [getsentry/sentry-elixir#204] opened 2017-09-06 14:16 UTC
Been having an issue where our application complains about an undefined function, when we have a filter applied to the sentry configuration.
In fact we have pretty much exactly the config as described here:
https://github.com/getsentry/sentry-elixir/blob/master/docs/index.rst#filtering-events

This only seems to occur when I use the following command: `mix sentry.send_test_event`
When running locally, I can iex and run: `Sentry.capture_exception(:exception)`
That does work and I get an event in Sentry.

Error I'm get:
```
Sending test event...
** (UndefinedFunctionError) function Claim.SentryEventFilter.exclude_exception?/2 is undefined (module Claim.SentryEventFilter is not available)
    Claim.SentryEventFilter.exclude_exception?(%RuntimeError{message: "Testing sending Sentry event"}, nil)
    (sentry) lib/sentry.ex:123: Sentry.capture_exception/2
    (sentry) lib/mix/tasks/sentry.send_test_event.ex:49: Mix.Tasks.Sentry.SendTestEvent.maybe_send_event/0
    (mix) lib/mix/task.ex:294: Mix.Task.run_task/3
    (mix) lib/mix/cli.ex:58: Mix.CLI.run_task/2
```
When the following is in the configuration:
```
config :sentry, filter: Claim.SentryEventFilter,
```
```
defmodule Claim.SentryEventFilter do
  @behaviour Sentry.EventFilter

  def exclude_exception?(%Elixir.Phoenix.Router.NoRouteError{}, :plug), do: true
  def exclude_exception?(_exception, _source), do: false
end
```

When the filter is removed, the test event sends normally with `mix sentry.send_test_event`.

Wondering if anyone else has seen this issue, just don't want to remove the filter, but would like to be able to send the test event for verification.

Or any tips on what could be the issue? I was wondering if the 'nil' part in the error was not being handled properly via mix?

**Comment by mitchellhenke** [comment] 2017-09-06 16:07
Thanks for opening this @hawksight, it definitely seems like there is a bug.  I will take a look into this and see where the issue is!

**Comment by mitchellhenke** [comment] 2017-09-06 22:52
I've opened https://github.com/getsentry/sentry-elixir/pull/206 which should fix this issue.  Once it's been finalized and merged, I'll do a point release.

**Closed** 2017-09-06 23:27 UTC
Labels: bug

**Comment by hawksight** [comment] 2017-09-07 09:27
Thank you @mitchellhenke - tested this morning and works perfectly now.
