### ISSUE TITLE
Absinthe integration with Sentry.PlugContext

### ISSUE THREAD

**Issue by lucazulian** [getsentry/sentry-elixir#494] opened 2022-02-09 11:00 UTC
Which SDK and version?
:absinthe, "1.4.16"
:sentry, "8.0.6"

### Steps to Reproduce
Create a simple Absinthe application with a simple graphql schema
```
defmodule MyApp.Router do
  @moduledoc false

  use Plug.Router
  plug Sentry.PlugContext

  forward "/graphiql",
     to: Absinthe.Plug.GraphiQL,
      init_opts: [
        schema: MyApp.Graphql.Schema,
        interface: :simple
      ]
end
```

### Expected Result
With the previous example the url `https://localhost:80/graphiql` returns 404 but moving the line `plug Sentry.PlugContext` after the `forward "/graphiql"` configuration it returns the correct page.

**Comment by mitchellhenke** [comment] 2022-02-13 17:41
Thanks for reporting this! It's pretty puzzling since `Sentry.PlugContext` doesn't modify the `conn` or return a status. I'm unfortunately unfamiliar with Absinthe. Would you be able to provide a minimal reproduction as a repo?

**Comment by mitchellhenke** [comment] 2022-05-03 13:27
Closing this for now 🙂

**Closed by mitchellhenke** 2022-05-03 13:27 UTC
