### ISSUE TITLE
Sentry not reporting exception

### ISSUE THREAD

**Issue by samphilipd** [getsentry/sentry-elixir#319] opened 2018-11-29 14:24 UTC
### Environment

* Elixir version (elixir -v):

1.7.3

* Erlang/OTP version (erl):

21.0.8

* Sentry version (mix deps):

7.0.3

* Operating system:

Linux

### Description

We have a class of error in our logs that was not reported by sentry.

```
Postgrex.Protocol (#PID<0.3255.0>) disconnected: ** (DBConnection.ConnectionError) client #PID<0.6480.2> exited
```

We have this line in our core OTP application:

`{:ok, _} = Logger.add_backend(Sentry.LoggerBackend)`

### Expected Behavior

I expected Sentry to report the exception.

### Actual Behavior

The exception is not showing up in sentry.

### Steps to Reproduce

???

**Comment by mitchellhenke** [comment] 2018-11-29 20:53
Thanks for opening an issue!

The `LoggerBackend` does not report every error log to Sentry, but only ones in which a crash happens (and it's an area that can always be improved).

In the case of DBConnection being unable to connect, the result of that log is a `Logger.error` call, which doesn't include the metadata around process crashes: https://github.com/elixir-ecto/db_connection/blob/59596188705a92a5b2fe0103c71df40c628be907/lib/db_connection/connection.ex#L87-L89

Some users do want every log with an `:error` level to be sent to Sentry (which is what https://github.com/SimonWoolf/sentry-logger-backend aims to do).  I'm not sure on a good way to include these types of errors without also including the noise of the other `:error` level logs, but it's perhaps worth exploring a way to report specific cases?

If you have ideas, I'm open to a discussion on the best way to handle it 🙂

**Comment by mitchellhenke** [comment] 2018-12-11 15:24
I'm happy to reopen and have a discussion on this issue, but will be closing it for now.

**Closed by mitchellhenke** 2018-12-11 15:24 UTC
Labels: question

**Comment by rodrigues** [comment] 2020-02-05 19:30
Hi @mitchellhenke !

I was surprised to know today about this behaviour.

Noticed that many error logs didn't get to Sentry, and after digging into your logger backend code, found out they were being ignored by design.

In Elixir, sometimes error is returned with tuples (not raising), and we'd still like to log these errors.

Sharing the alt solution I'll try for now, as it may be useful to someone else in the same situation, or you might want to incorporate this behaviour change in sentry's logger backend in some way 🙂

Cheers!

----------------------

I'm creating a custom backend that gets these kind of errors and sends them directly using `Sentry.send_event/1`:

```elixir
  # … pretty much same boilerplate as sentry's logger backend
  # … (work in progress)
  def handle_event({:error, _gl, {Logger, msg, _ts, meta}}, state) do
     %{include_logger_metadata: include_logger_metadata} = state

     extra =
       if include_logger_metadata do
         %{logger_metadata: safe_metadata(meta)}
       else
         %{}
       end

     case Keyword.get(meta, :crash_reason) do
       nil ->
         # only run if there's no exception associated with error
         event =
           Event.create_event(
             message: msg,
             extra: extra,
             exception: [%{type: "Error", value: msg, module: "Logger"}]
           )

         _ = Sentry.send_event(event)
         :ok

       _ ->
         :ok
     end

     {:ok, state}
   end
```

**Comment by mitchellhenke** [comment] 2020-02-05 20:25
@rodrigues could you share some examples of errors you'd like to have reported, but are not currently (as they don't have `:crash_reason`)?

**Comment by rodrigues** [comment] 2020-02-05 21:03
Hi @mitchellhenke, sure, basically anything like the below doesn't go to sentry:

```elixir
# call logger with error severity level, instead of raising
Logger.error("Error message", some: 0, meta: 1, data: 2)
```

For example, every x secs I call a function that processes something and I don't need/want to raise:

```elixir
@spec process() :: :ok
def process do
  process_things()
  |> and_a_bit_more()
  |> and_call_an_api_for_instance()
  |> case do
    {:ok, data} ->
       # … do something
       log_info("Things worked fine")

    {:error, _} = error ->
       log_error("Problem when calling API", error: error)
  end
end
```

Another example, a function that can return an ok or error tuple, it's called by another application, but we want to log when it's going to return error data:

```elixir
@spec foo(…) :: {:ok, Thingy.t()} | {:error, term()}
def foo(input) do
  input
  |> do()
  |> things()
  |> case do
    {:error, _} = error ->
      log_error("Problem fooing", error: error)
      error

    other ->
      other
  end
end
```

Cheers!

**Comment by mitchellhenke** [comment] 2020-02-05 21:27
Thanks for the detail. Options to consider for cases like that is to use `Sentry.capture_exception` or `Sentry.capture_message` directly or a Logger backend that sends every event to Sentry (like linked above).

The two issues I'm trying to be mindful of around this is people and libraries use Logger differently, so capturing all error messages could be noisy, and there is a limit to how many events can be reported for a given user.

The other aspect is that unless a user and library has constructed metadata or context around the Logger event, the Sentry event itself may be less useful or actionable.

I'm not sure I can add the above without those issues being addressed.

**Comment by rodrigues** [comment] 2020-02-05 22:16
> The two issues I'm trying to be mindful of around this is people and libraries use Logger differently, so capturing all error messages could be noisy, and there is a limit to how many events can be reported for a given user.

Good points, bringing just some thoughts about how I think this could go smoothly:

- If it can be configurable (`false` by default), and the users that want to enable it could choose, I think it would be already awesome 👍
- You could also rely on some log metadata to decide whether to send event or not in a per-log-event basis (e.g. `sentry: true` means go ahead).
- EventFilter behaviour could evolve to support this case also, and filter any event, not only exceptions – so someone could filter out events with certain message regex or certain metadata.

> The other aspect is that unless a user and library has constructed metadata or context around the Logger event, the Sentry event itself may be less useful or actionable.

Yes, definitely, the quality of the error would be as good as one would report it, hehe, and I think that's fine 😄

Many of these error logs we have are much more usable/actionable than `nil.field/0` crash kind of error reports, as they come with a human message explaining the scenario that shouldn't have happened, and the surrounding metadata I'd need to investigate it further.
