### ISSUE TITLE
Sentry report is not including set context

### ISSUE THREAD

**Issue by LiyangW** [getsentry/sentry-elixir#349] opened 2019-06-10 20:53 UTC
### Environment

* Elixir version (elixir -v): Elixir 1.8.1 
* Erlang/OTP version (erl): Erlang/OTP 21
* Sentry version (mix deps): sentry 7.0.6
* Operating system: MacOS 

### Description
I am using `sentry`'s `Sentry.Context.set_user_context` under `exq` processes.  I have set the context by using 
```     
def perform(args) do
    Sentry.Context.set_user_context(args)
    IO.inspect Sentry.Context.get_all()
    ......
end
```
, and during my function's running, i am seeing 
```
%{
  breadcrumbs: [],
  extra: %{},
  request: %{},
  tags: %{},
  user: %{"email" => "asdfasf@.afac"}
}
``` 
in my console.  But on my `sentry` `issues` website, I am not seeing any user tag.  

### Expected Behavior
`user` tag on `sentry` `issues` website

### Actual Behavior
Not seeing `user` tag

**Comment by mitchellhenke** [comment] 2019-06-11 15:34
@LiyangW Thanks for opening an issue!

My hunch is that this is because the job is running in a separate process than the one that sends the exception, and the context gets lost since the context is stored in the process dictionary.

Potential solutions are to make use of the callback described [here](https://github.com/getsentry/sentry-elixir/issues/337#issuecomment-489783315), though it may duplicate then.

Are you using Sentry.LoggerBackend?

**Comment by LiyangW** [comment] 2019-06-11 16:41
@mitchellhenke Thanks for answering me back!

I am using 
```{:ok, _} = Logger.add_backend(Sentry.LoggerBackend)```  
inside my `App.Appplication`'s `start` function.  

Originally, I thought it is because of the separate processes issue as well, so I actually moved the `Sentry.Context.set_user_context` to the worker functions.  

Therefore the `exq` command 
```{:ok, _ack} = Exq.Enqueuer.enqueue(Exq, "file_uploading", FileUploadWorker, [args])```
create a worker process by calling `worker`'s `perform` function and the `perform` function contains  `Sentry.Context.set_user_context`.  

In my understanding, the above procedure would make sure each process has its `user_context` set up, after being spawned.  Thanks for the help!

**Comment by mitchellhenke** [comment] 2019-06-13 14:13
Yep, that's the right idea, but unfortunately the worker process is separate from the LoggerBackend process that receives the event.

Because of that, I'm not sure how best to handle this.  `try/rescue` with a manual sending of event and context would "solve" it in that the context would then be included, but is more of a hassle.

I'll be able to dig into this a bit further to see if a more complete solution is feasible.

**Comment by barkerja** [comment] 2020-02-04 17:50
Would it make sense to potentially explore `:persistent_store` which was introduced in OTP 21.2? It's a VM-wide storage accessible from all processes/modules.

**Comment by mitchellhenke** [comment] 2020-02-14 21:35
Indeed, something backed with a core feature and has no dependencies would be preferable.

(linking #383, as these are related)

**Comment by 1player** [comment] 2020-11-06 16:00
Any update on this issue? Not having context makes debugging much harder for us.

**Comment by mitchellhenke** [comment] 2020-11-07 16:37
There were some improvements over the past 6 months or so that should resolve most of these issues.

@1player are you using exq and experiencing this problem?

**Comment by 1player** [comment] 2020-11-08 13:23
No I'm not using exq, I'm just noticing my async processes sometimes fail, but the context isn't sent to Sentry. It used to, the code hasn't changed in months, so the only suspect is the Sentry client library, which has been updated since, failing to push that additional context data.

**Comment by mitchellhenke** [comment] 2020-11-11 14:51
@1player Hm, that would be a significant bug if the tests are passing and you're experiencing that. Could you provide a minimal way to reproduce?

**Comment by 1player** [comment] 2020-12-08 12:55
My bad, there is no regression. I'm having the same issue as others where context is set on another process than the one that actually sends the exception, and I'll have to work around that until this library is able to work across processes (using :persistent_term) or the docs clarify the best way to deal with this common problem.

**Comment by Shelvak** [comment] 2020-12-13 18:27
Hi there, I hit the same problem with Exq, The only workaround that works for me is "double exception" with:
```elixir
  def perform(args) do
    #code
  rescue
    ex ->
      Sentry.capture_exception(ex,
        stacktrace: __STACKTRACE__,
        extra: %{....},
        tags: %{worker: __MODULE__}
      )

    raise ex # <- this create another event without context, the "common flow".
  end
```

Any other idea?

**Comment by mitchellhenke** [comment] 2020-12-27 16:28
I found a small change that may fix this in Exq: https://github.com/akira/exq/pull/436

**Comment by mitchellhenke** [comment] 2021-01-02 16:50
With that pull request merged, I'm going to close this issue for now 🙂

**Closed by mitchellhenke** 2021-01-02 16:50 UTC
Labels: question
