### ISSUE TITLE
Logger backend errors

### ISSUE THREAD

**Issue by coop** [getsentry/sentry-elixir#637] opened 2023-10-30 07:32 UTC
### Environment

dev, staging and production

What version are you running? Etc

I was originally running erlang 25.3 and elixir 1.14.x and I saw the same issue. I upgraded to see if it was something to do with a recent logger upgrade but I'm still seeing the same issue.

```
❯ cat .tool-versions
erlang 26.1.2
elixir 1.15.7-otp-26
```

Sentry v9.1.0

### Steps to Reproduce

I have an existing application but the config is fairly standard:

```
# config/config.exs
config :sentry,
  environment_name: Mix.env(),
  included_environments: [:stag, :prod],
  filter: App.Sentry,
  before_send_event: {App.Sentry, :before_send},
  enable_source_code_context: true,
  root_source_code_paths: [File.cwd!()]
```

### Expected Result

Sentry logger shouldn't crash.

### Actual Result

```
ts=2023-10-30T17:24:13.073 level=error msg="[logger: :callback_crashed, process: :logger, reason: {:error, {:badkey, :config}, [{:erlang, :map_get, [:config, %{id: :sentry_handler, module: Sentry.LoggerHandler, level: :all, filter_default: :log, filters: [], formatter: {:logger_formatter, %{}}}], [error_info: %{module: :erl_erts_errors}]}, {Map, :update!, 3, [file: ~c\"lib/map.ex\", line: 318]}, {Sentry.LoggerHandler, :adding_handler, 1, [file: ~c\"lib/sentry/logger_handler.ex\", line: 123]}]}]"
```

**Comment by coop** [comment] 2023-10-30 07:34
In my application start/2 callback I'm setting a few values too:

```elixir
Application.put_env(:sentry, :dsn, config.dsn)
Application.put_env(:sentry, :environment_name, config.env)
Application.put_env(:sentry, :release, config.release)
```

**Comment by whatyouhide** [comment] 2023-10-30 07:47
Hey @coop, thanks for reporting this. This was fixed in https://github.com/getsentry/sentry-elixir/pull/635, can you try out `master` please? 🙃 

Also, until a new version containing the bug fix comes out, you'll have to explicitly pass in the `:config` key when adding the `Sentry.LoggerHandler`. With an empty config, it would look like this:

```elixir
:logger.add_handler(:my_sentry_logger_handler, Sentry.LoggerHandler, %{config: %{}})
```

**Comment by whatyouhide** [comment] 2023-10-30 07:48
*Duplicate of https://github.com/getsentry/sentry-elixir/issues/630*.

**Closed by whatyouhide** 2023-10-30 07:47 UTC

**Comment by coop** [comment] 2023-10-30 07:51
Sorry about that @whatyouhide - I looked through the open issues but didn't see anything. Should have looked at the closed ones. Thanks, this fixed it.
