### ISSUE TITLE
Erlang error: {:EXIT, {:noproc, {GenServer, :call, [Sentry.TaskSupervisor,

### ISSUE THREAD

**Issue by brunohkbx** [getsentry/sentry-elixir#478] opened 2021-05-19 18:02 UTC
### Environment
erlang 23.1.1
elixir 1.11.0-otp-23
phoenix "~> 1.5"

How do you use Sentry?
Sentry SaaS (sentry.io)

Which SDK and version?
e.g: Elixir "~> 8.0"

### Steps to Reproduce

1. Set up sentry in an umbrella phoenix app following the docs [here](https://docs.sentry.io/platforms/elixir/)
2. Deploy it to Heroku
3. Get the following error during each deploy 

### Expected Result
Shouldn't throw any errors

### Actual Result
```
Erlang error: {:EXIT, {:noproc, {GenServer, :call, [Sentry.TaskSupervisor, {:start_task, [{:"server@e26c12c3-fa2d-4590-b295-311e2960a816", Logger, #PID<0.421.0>}, [#PID<0.421.0>], {:erlang, :apply, [#Function<2.95599806/0 in Sentry.Client.do_send_event/3>, []]}], nil, nil}, :infinity]}}}
```

Maybe related to https://github.com/getsentry/sentry-elixir/issues/339 ?

**Comment by subsetpark** [comment] 2021-05-20 17:57
I think I'm experiencing the same issue. Mine is not when deploying - but because this message says `do_send_event`, I'm going to guess it's the same, since that's when mine happens: when the LoggerBackend tries to crash a process.

# Environment 

erlang 23.3.1
elixir 1.11.4-otp-23

# Mix.lock entry

```
"sentry": {:hex, :sentry, "8.0.5", "5ca922b9238a50c7258b52f47364b2d545beda5e436c7a43965b34577f1ef61f", [:mix], [{:hackney, "~> 1.8", [hex: :hackney, repo: "hexpm", optional: true]}, {:jason, "~> 1.1", [hex: :jason, repo: "hexpm", optional: true]}, {:plug, "~> 1.6", [hex: :plug, repo: "hexpm", optional: true]}, {:plug_cowboy, "~> 2.3", [hex: :plug_cowboy, repo: "hexpm", optional: true]}], "hexpm", "4972839fdbf52e886d7b3e694c8adf421f764f2fa79036b88fb4742049bd4b7c"},
```

# Steps to Reproduce

1. Specify the Sentry.LoggerBackend in your logger config:

```

config :logger,
  handle_otp_reports: true,
  handle_sasl_reports: true,
  backends: [:console, Sentry.LoggerBackend],
  utc_log: true
```

2. Crash a worker process executed with `start_link`.

```
iex(api@X.X.X.X)1> Events.Consumer.Worker.start_link(EventConsumers.Auditor.Consumer, %Core.Projects.AssetDeleted{item: %{id: "some id"}})
```

(That's obviously domain-specific, but it's a call that we expect to fail, and does result in a crash of the spawned process)

# Result

```
{:ok, #PID<0.7840.0>}
iex(api@X.X.X.X)2> 17:48:07.267 erl_level=warning application=events consumer=EventConsumers.Auditor.Consumer domain=elixir event=%Core.Projects.AssetDeleted{Events.Broadcaster.TraceId => nil, :assoc => nil, :context => nil, :ignore => nil, :item => %{id: "some id"}, :updater => nil} event_type=Core.Projects.AssetDeleted file=lib/events/consumer/worker.ex function=set_trace_id/2 line=59 mfa=Events.Consumer.Worker.set_trace_id/2 module=Events.Consumer.Worker pid=<14324.7840.0> [warn]  [Events] Received event with missing trace_id
17:48:07.267 erl_level=error application=events consumer=EventConsumers.Auditor.Consumer domain=elixir error=%KeyError{key: :project_id, message: nil, term: %{id: "some id"}} event_item_id=some id event_type=Core.Projects.AssetDeleted file=lib/events/consumer/worker.ex function=log_error/4 line=87 mfa=Events.Consumer.Worker.log_error/4 module=Events.Consumer.Worker pid=<14324.7840.0> [error] [Events] Failed to process event with error %KeyError{key: :project_id, message: nil, term: %{id: "some id"}}
** (EXIT from #PID<0.7816.0>) shell process exited with reason: an exception was raised:
    ** (KeyError) key :project_id not found in: %{id: "some id"}
        (event_consumers 0.1.0) lib/event_consumers/auditor/impls/assets.ex:46: EventConsumers.Auditor.Auditable.Core.Projects.AssetDeleted.audit/1
        (event_consumers 0.1.0) lib/event_consumers/auditor/consumer.ex:24: EventConsumers.Auditor.Consumer.handle_event/1
        (events 0.1.0) lib/events/consumer/worker.ex:37: Events.Consumer.Worker.try_handle_event/2
        (events 0.1.0) lib/events/consumer/worker.ex:27: anonymous fn/2 in Events.Consumer.Worker.start_link/2
        (telemetry 0.4.3) /opt/app/deps/telemetry/src/telemetry.erl:272: :telemetry.span/3
        (elixir 1.11.4) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
        (stdlib 3.14.1) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
                       
Interactive Elixir (1.11.4) - press Ctrl+C to exit (type h() ENTER for help)
iex(api@X.X.X.X1> 17:48:07.283 erl_level=error domain=otp.elixir pid=<14324.7840.0> [error] Task #PID<14324.7840.0> started from #PID<14324.7816.0> terminating
** (KeyError) key :project_id not found in: %{id: "some id"}
    (event_consumers 0.1.0) lib/event_consumers/auditor/impls/assets.ex:46: EventConsumers.Auditor.Auditable.Core.Projects.AssetDeleted.audit/1
    (event_consumers 0.1.0) lib/event_consumers/auditor/consumer.ex:24: EventConsumers.Auditor.Consumer.handle_event/1
    (events 0.1.0) lib/events/consumer/worker.ex:37: Events.Consumer.Worker.try_handle_event/2
    (events 0.1.0) lib/events/consumer/worker.ex:27: anonymous fn/2 in Events.Consumer.Worker.start_link/2
    (telemetry 0.4.3) /opt/app/deps/telemetry/src/telemetry.erl:272: :telemetry.span/3
    (elixir 1.11.4) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
    (stdlib 3.14.1) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Function: #Function<0.32327229/0 in Events.Consumer.Worker>
    Args: []
17:48:07.376 erl_level=error domain=otp file=gen_event.erl function=report_error/5 line=792 mfa=:gen_event.report_error/5 module=gen_event pid=<0.101.0> registered_name=Logger [error] :gen_event handler Sentry.LoggerBackend installed in Logger terminating
** (stop) exited in: GenServer.call(Sentry.TaskSupervisor, {:start_task, [{:"remsh20a9447e-api@X.X.X.X", Logger, #PID<0.101.0>}, [#PID<0.101.0>], {:erlang, :apply, [#Function<2.95599806/0 in Sentry.Client.do_send_event/3>, []]}], nil, nil}, :infinity)
    ** (EXIT) no process: the process is not alive or there's no process currently associated with the given name, possibly because its application isn't started
Last message: {:error, #PID<0.77.0>, {Logger, ["Task #PID<14324.7840.0> started from #PID<14324.7816.0> terminating", [[10 | "** (KeyError) key :project_id not found in: %{id: \"some id\"}"], ["\n    " | "(event_consumers 0.1.0) lib/event_consumers/auditor/impls/assets.ex:46: EventConsumers.Auditor.Auditable.Core.Projects.AssetDeleted.audit/1"], ["\n    " | "(event_consumers 0.1.0) lib/event_consumers/auditor/consumer.ex:24: EventConsumers.Auditor.Consumer.handle_event/1"], ["\n    " | "(events 0.1.0) lib/events/consumer/worker.ex:37: Events.Consumer.Worker.try_handle_event/2"], ["\n    " | "(events 0.1.0) lib/events/consumer/worker.ex:27: anonymous fn/2 in Events.Consumer.Worker.start_link/2"], ["\n    " | "(telemetry 0.4.3) /opt/app/deps/telemetry/src/telemetry.erl:272: :telemetry.span/3"], ["\n    " | "(elixir 1.11.4) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2"], ["\n    " | "(stdlib 3.14.1) proc_lib.erl:226: :proc_lib.init_p_do_apply/3"]], "\nFunction: #Function<0.32327229/0 in Events.Consumer.Worker>", "\n    Args: []"], {{2021, 5, 20}, {17, 48, 7, 283}}, [erl_level: :error, callers: [#PID<14324.7816.0>], crash_reason: {%KeyError{key: :project_id, message: nil, term: %{id: "some id"}}, [{EventConsumers.Auditor.Auditable.Core.Projects.AssetDeleted, :audit, 1, [file: 'lib/event_consumers/auditor/impls/assets.ex', line: 46]}, {EventConsumers.Auditor.Consumer, :handle_event, 1, [file: 'lib/event_consumers/auditor/consumer.ex', line: 24]}, {Events.Consumer.Worker, :try_handle_event, 2, [file: 'lib/events/consumer/worker.ex', line: 37]}, {Events.Consumer.Worker, :"-start_link/2-fun-0-", 2, [file: 'lib/events/consumer/worker.ex', line: 27]}, {:telemetry, :span, 3, [file: '/opt/app/deps/telemetry/src/telemetry.erl', line: 272]}, {Task.Supervised, :invoke_mfa, 2, [file: 'lib/task/supervised.ex', line: 90]}, {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 226]}]}, domain: [:otp, :elixir], error_logger: %{tag: :error_msg}, gl: #PID<0.77.0>, pid: #PID<14324.7840.0>, report_cb: &Task.Supervised.format_report/1, sentry: %{extra: %{consumer: "EventConsumers.Auditor.Consumer", event: "%Core.Projects.AssetDeleted{Events.Broadcaster.TraceId => nil, :assoc => nil, :context => nil, :ignore => nil, :item => %{id: \"some id\"}, :updater => nil}"}}, time: 1621532887283937]}}
State: %Sentry.LoggerBackend{capture_log_messages: false, excluded_domains: [:cowboy], level: :error, metadata: []}
17:48:07.382 erl_level=error domain=otp file=gen_server.erl function=error_info/7 line=943 mfa=:gen_server.error_info/7 module=gen_server pid=<0.105.0> [error] GenServer #PID<0.105.0> terminating
** (stop) {:EXIT, {:noproc, {GenServer, :call, [Sentry.TaskSupervisor, {:start_task, [{:"remsh20a9447e-api@X.X.X.X Logger, #PID<0.101.0>}, [#PID<0.101.0>], {:erlang, :apply, [#Function<2.95599806/0 in Sentry.Client.do_send_event/3>, []]}], nil, nil}, :infinity]}}}
Last message: {:gen_event_EXIT, Sentry.LoggerBackend, {:EXIT, {:noproc, {GenServer, :call, [Sentry.TaskSupervisor, {:start_task, [{:"remsh20a9447e-api@X.X.X.X Logger, #PID<0.101.0>}, [#PID<0.101.0>], {:erlang, :apply, [#Function<2.95599806/0 in Sentry.Client.do_send_event/3>, []]}], nil, nil}, :infinity]}}}}
State: Sentry.LoggerBackend
```

**Comment by mitchellhenke** [comment] 2021-05-23 14:24
@subsetpark Thanks for the detail! Could you elaborate on `when the LoggerBackend tries to crash a process.`?

The issue seems to be that the handler can be re-attached and receive messages before the Sentry application and its children (including the TaskSupervisor) are back up?

**Comment by mitchellhenke** [comment] 2021-09-28 23:08
Closing this issue for now, but happy to look closer with more details.

**Closed by mitchellhenke** 2021-09-28 23:08 UTC
