### ISSUE TITLE
Double reporting of errors

### ISSUE THREAD

**Issue by scottmessinger** [getsentry/sentry-elixir#486] opened 2021-08-17 14:37 UTC
### Environment

How do you use Sentry?
Sentry SaaS (sentry.io) 

Which SDK and version?
Elixir - sentry@8.0.5

### Steps to Reproduce

Not quite sure how to reproduce, but here's what I'm seeing. I have a Phoenix Controller and a request runs into a `MatchError`. I get two reports: one for `MatchError` and a `Sentry.CrashError`. They have different contexts but are describing the same error. I would expect I'd get one report from Sentry that combines the context visible in both reports. 

### First Error Report: `Match Error` with a stacktrace but little context

In a plug, I'll get an error like this: `Match Error: no match...`

<img width="714" alt="image" src="https://user-images.githubusercontent.com/100121/129743848-aa1f70c0-908c-4bae-a9a8-6ffcb416da07.png">

I get:
- 👍 A nice stacktrace!
- 👎 No information about the request
- 👎 Little extra information

### Second Error Report `Sentry.CrashError` with no stacktrace but nice context

Immediately after, I get another issue from Sentry for the same error but wrapped: `(Sentry.CrashError ** (exit) {{{%MatchError{term:....`

<img width="703" alt="image" src="https://user-images.githubusercontent.com/100121/129744382-815bcac9-f06a-4d3a-bdbd-2c930d8b283f.png">

I get:
- 👎 No stack trace
- 👍 All the information about the request
- 👍 All the information about the user that I've set as Sentry context.

### Expected Result

I want both of these to be combined into one error. I'd like to see one error with:
- Stacktrace
- Information about the http request
- All the information I set as Sentry.context

### Actual results

I think I summed it up above, but let me know if I'm leaving anything out or am unclear! I'm hoping it's a config error on my part or something else I can adjust.

**Comment by mitchellhenke** [comment] 2021-09-06 14:22
Hi @scottmessinger, thanks for opening an issue!

It looks like the error is being captured by both `Sentry.PlugCapture` and `Sentry.LoggerBackend`. This should be excluded by the LoggerBackend.

The stacktrace suggests to me that it was a MatchError in the Phoenix Endpoint, so I tried reproducing what you're seeing myself, but I'm not able to generate a double error. Do you have any configuration for `Sentry.LoggerBackend`?

**Comment by mitchellhenke** [comment] 2021-09-28 23:09
Closing this issue for now, but happy to take a further look with more details.

**Closed by mitchellhenke** 2021-09-28 23:09 UTC
